version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./unmocked_unit_test.py
          name: Project2 M3 Test
      - run:
      name: Wait for Postgres to start
      command: dockerize -wait tcp://localhost:5432 -timeout 1m

      
workflows:
  main:
    jobs:
      - build-and-test

